### PR TITLE
UForm for Swift  🍏 🐦 

### PR DESCRIPTION
**Pull request by ashvardanian**
Apple has over 2 billion devices worldwide.
Most of them are equipped with powerful GPUs.
Time to bring multimodal AI to every pocket.
Time to bring UForm to 🍏 

---

Related PRs:

- https://github.com/huggingface/swift-transformers/pull/89
- https://github.com/huggingface/swift-transformers/pull/90

### CODE REVIEW

**Comment by lin72h** [comment]
Very excited!

**Comment by lin72h** [comment]
Ash you rock!

**Comment by ashvardanian** [comment]
Thanks @lin72h 😊

It's very experimental for now. CoreML is very far from feature complete, and the rest of the ecosystem is just as immature, but this should be a step in the right direction. I'll file a longer report on how it works and how to use it in different languages in the next days.

Stay tuned 🤗

**Pull request merged**
