### PR TITLE
[Refactor] Modular package organisation, pre-commit linting suite

### PR DESCRIPTION
**Pull request by lmmx**
I wanted to review the code here to see how it worked, and I did some refactoring so I could read it more easily.

- ba55b97 introduces an explicit namespace (using `__all__` variables) and splits apart classes which do not need to share a module, for ease of reading individual components.
  - This is purely a reorganisation with no modification to the interface (in case anyone is relying on the current one)
  - I checked this work with `ruff` and followed its guidance to avoid using `*` imports so imports are also explicit
  - I also switched to relative imports which are more concise when using multiple levels:

```sh
$ tree src/uform
src/uform
├── chat.py
├── gen_model.py
├── __init__.py
├── models
│   ├── encoders
│   │   ├── __init__.py
│   │   ├── network_layers.py
│   │   ├── text
│   │   │   ├── block.py
│   │   │   ├── encoder.py
│   │   │   └── __init__.py
│   │   └── visual
│   │       ├── block.py
│   │       ├── encoder.py
│   │       └── __init__.py
│   ├── image_utils.py
│   ├── __init__.py
│   ├── triton.py
│   └── vlm.py
└── setup_model.py

4 directories, 16 files
```

- aca18fe  adds a pre-commit config with `ruff`, `toml-sort` and `pyupgrade` (set to 3.7+).  The 2 lines at the start will run this on CI (via https://pre-commit.ci) for the repo - this avoids requiring contributors to set this tool up
- 6dd0e3f runs the pre-commit suite, which made some very minor adjustments (newlines at end of file etc).

### CODE REVIEW

**Comment by ashvardanian** [comment]
Looks very nice, thank you @lmmx! I am pretty sure there will be collisions with #57, so give us a bit of time to find the optimal way to merge it 🤗 

In the meantime, if you have any other recommendations about this or other repos I maintain (like [SimSIMD](https://github.com/ashvardanian/simsimd)), please let us know!

**Comment by lmmx** [comment]
Ah I just got the benchmarks to run and looks like I have made a mistake, I'm getting a warning from running the bench script (whereas no warning from the `PyPI` packaged version). Will put back to draft until I find. I'll take a look thanks Ash!

**Comment by ashvardanian** [comment]
Hi @lmmx! Thank you for the contribution!

We've looked into it with a team and can't merge it in its entirety right now, as it will introduce structural differences between public UForm and our private training repositories.

That said, the CI upgrades look interesting! Would you be open to reverting the structural changes and keeping just the CI? 

Thanks again!

**Comment by lmmx** [comment]
Fair enough, sure I will cancel this PR and make a fresh one :inbox_tray:

**Pull request closed without merging**
